/**
 * OpenApi
 * Descripcion nuevo backend NestJS
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface LoginResponseDto { 
    user: User;
    token: string;
}

