/**
 * OpenApi
 * Descripcion nuevo backend NestJS
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    /**
     * The unique identifier of the user
     */
    _id: string;
    /**
     * The email of the user
     */
    email: string;
    /**
     * The name of the user
     */
    name: string;
    /**
     * The password of the user
     */
    password: string;
    /**
     * The active status of the user
     */
    isActive: boolean;
    /**
     * The roles of the user
     */
    roles: Array<string>;
}

